### ISSUE TITLE
Builds are broken!

### ISSUE THREAD

**Issue by c4lliope** [elixir-desktop/runtimes#4]
I forked this codebase to see if I could get a copy of OTP-26.1.2 compiled.

I'm seeing errors though regardless of the OTP version I use,
both on GitHub CI and on my local machine (podman and docker both).

Here's a quick summary of my failures:
https://github.com/c4lliope/ex-mobile/actions/workflows/ci.yml

Can you help lend direction on how you ran the CI pipeline properly?

- - -

Locally, I'm seeing an error similar to:
https://github.com/erlang/otp/issues/3826

only I see: `./configure: not found` inside `dockcross/android-*`
as clarification, this happens for both OTP 25 and OTP 26.

```
Step 16/21 : WORKDIR /work/otp
 ---> Using cache
 ---> 2f25ba8511b9
Step 17/21 : RUN ./otp_build configure --disable-jit --with-ssl=/usr/local/openssl/ --disable-dynamic-ssl-lib --without-javac --without-odbc --without-wx --without-debugger --without-observer --without-cdv --without-et --xcomp-conf=xcomp/erl-xcomp-arm-android.conf
 ---> Running in 720e7a856f54

*
* Configuring the bootstrap build system...
*

/work/otp/configure  --cache-file=/dev/null --enable-bootstrap-only
./otp_build: 1: eval: ./configure: not found
The command '/bin/sh -c ./otp_build configure --disable-jit --with-ssl=/usr/local/openssl/ --disable-dynamic-ssl-lib --without-javac --without-odbc --without-wx --without-debugger --without-observer --without-cdv --without-et --xcomp-conf=xcomp/erl-xcomp-arm-android.conf' returned a non-zero code: 1
** (MatchError) no match of right hand side value: {%IO.Stream{device: :standard_io, raw: true, line_or_bytes: :line}, 1}
    (runtimes 0.1.0) lib/runtimes.ex:37: Runtimes.docker_build/2
    (runtimes 0.1.0) lib/mix/tasks/package_android_runtime.ex:26: Mix.Tasks.Package.Android.Runtime.build/1
    (runtimes 0.1.0) lib/mix/tasks/package_android_runtime.ex:49: Mix.Tasks.Package.Android.Runtime.buildall/1
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.7) lib/mix/cli.ex:92: Mix.CLI.run_task/2
    /home/calliope/.nix-profile/bin/mix:2: (file)
calliope@chesapeake:~/base/code/ex-mobile/ >
```

**Comment by dominicletz** [comment]
Hey @c4lliope I've pushed a fix that makes the previous OTP versions work: https://github.com/elixir-desktop/runtimes/commit/977d46b611057913a9dd8c909d8782e9e2219c02
